# Inciso 6. Presentación del problema

Dado un arreglo de 10x10x10 de ceros, establece (i, j, k) = 1 sí, i es impar, j es par y
k es primo. En otras palabras, establece esos elementos a 1: (1, 0, 2), (1, 0, 3), (1, 0, 5), (1, 0, 7),(1, 2, 2)...

# Resolución

In [1]:
import numpy as np


## Hacemos el arreglo de 10x10x10

In [2]:
arreglo = np.zeros((10, 10, 10), dtype=int)
print(arreglo)

[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0

## Verificar si un número es primo

In [3]:
def es_primo(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

## Crear máscaras para cada condición

In [4]:
i_impares = np.arange(10) % 2 == 1
j_pares = np.arange(10) % 2 == 0


In [5]:
k_primos = np.array([es_primo(k) for k in range(10)])

## Imprimir las máscaras para entender qué valores cumplen las condiciones

In [6]:
print("Impares:", np.where(i_impares)[0])
print("Pares:", np.where(j_pares)[0])
print("Primos:", np.where(k_primos)[0])

Impares: [1 3 5 7 9]
Pares: [0 2 4 6 8]
Primos: [2 3 5 7]


In [7]:
arreglo[i_impares[:, np.newaxis, np.newaxis] & 
        j_pares[np.newaxis, :, np.newaxis] & 
        k_primos[np.newaxis, np.newaxis, :]] = 1

# Resolución

## Clasos de prueba

In [8]:
test_cases = [
    # Casos que deberían ser 1 (i impar, j par, k primo)
    (1, 0, 2), (1, 0, 3), (1, 0, 5), (1, 0, 7),
    (1, 2, 2), (3, 0, 3), (5, 4, 5), (7, 6, 7),
    (9, 8, 2), (9, 8, 7),
    
    # Casos que deberían ser 0
    (0, 0, 2),  # i no es impar
    (1, 1, 2),  # j no es par
    (1, 0, 4),  # k no es primo
    (2, 2, 2),  # i no es impar, aunque j es par y k es primo
    (1, 3, 3),  # j no es par, aunque i es impar y k es primo
    (1, 0, 6),  # k no es primo, aunque i es impar y j es par
    (0, 1, 4)   # Ninguna condición se cumple
]

In [9]:
print("\nVerificacion de casos de prueba:")
print("--------------------------------")
for idx, (i, j, k) in enumerate(test_cases):
    valor_actual = arreglo[i, j, k]
    condiciones = []
    if i % 2 == 1: condiciones.append("i impar")
    if j % 2 == 0: condiciones.append("j par")
    if es_primo(k): condiciones.append("k primo")
    
    valor_esperado = 1 if len(condiciones) == 3 else 0
    estado = "✓" if valor_actual == valor_esperado else "✗"
    
    print(f"Test {idx+1}: ({i},{j},{k}) = {valor_actual} {estado}")
    print(f"  Condiciones cumplidas: {', '.join(condiciones) if condiciones else 'ninguna'}")



Verificacion de casos de prueba:
--------------------------------
Test 1: (1,0,2) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 2: (1,0,3) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 3: (1,0,5) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 4: (1,0,7) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 5: (1,2,2) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 6: (3,0,3) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 7: (5,4,5) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 8: (7,6,7) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 9: (9,8,2) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 10: (9,8,7) = 1 ✓
  Condiciones cumplidas: i impar, j par, k primo
Test 11: (0,0,2) = 0 ✓
  Condiciones cumplidas: j par, k primo
Test 12: (1,1,2) = 0 ✓
  Condiciones cumplidas: i impar, k primo
Test 13: (1,0,4) = 0 ✓
  Condiciones cumplidas: i impar, j par
Test 14: (2,2,2) = 0 ✓
  Condic